language: php ruby
cache:
  - bundler
before_install:
  - ci/install_ffmpeg
  - export PATH=`pwd`/ffmpeg:$PATH
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
rvm:
  - 2.1.1
script: phpunit
notifications:
  email:
    on_success: change