language: php
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mkdir ffmpeg
  - wget "http://ffmpeg.gusari.org/static/64bit/ffmpeg.static.64bit.latest.tar.gz"
  - tar xzf ffmpeg.static.64bit.latest.tar.gz -C ffmpeg
  - export PATH=`pwd`/ffmpeg:$PATH
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
script: phpunit
notifications:
  email:
    on_success: change