language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - ci/install_ffmpeg
  - export PATH=`pwd`/ffmpeg:$PATH

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

notifications:
  email:
    on_success: change